Added unit test case for CMLAtomTypeListTest.java
BlueObelisk/cmlxom pull request #18
Opened 2023-10-02 13:20 UTC by Gowrishankar04

#17 - Added unit test case for CMLAtomTypeListTest.java

2023-10-02 13:22 UTC, Gowrishankar04 commented
Hi @egonw - I have added unit test case for above mentioned file. Kindly review and provide feedback if any. Thanks!!

2023-10-02 17:31 UTC, egonw commented on src/test/java/org/xmlcml/cml/element/main/CMLAtomTypeListTest.java
> +package org.xmlcml.cml.element.main;
Please add a copyright/license statement. See for example the `CMLArrayListTest.java` file in this repository.

2023-10-02 17:31 UTC, egonw commented on src/test/java/org/xmlcml/cml/element/main/CMLAtomTypeListTest.java
> +        Assert.assertEquals("class should be CMLAtomTypeList: ", cmlAtomTypeList.getAttributeValue("atom"),
The error message does not seem to match the test. Please update.

2023-10-02 17:32 UTC, egonw requested changes
Two comments, otherwise looks good.

2023-10-03 17:56 UTC, Gowrishankar04 commented
@egonw  - Sure! let me make these changes and include other files as well. Thanks!!

2023-10-04 20:53 UTC, Gowrishankar04 commented
@egonw - Added unit test case for the below files:

CMLAtomTypeList.java, CMLBand.java, CMLBandList.java, CMLAxis.java, CMLXAxis.java, CMLYAxis.java.

Kindly review and merge the PR.

Thanks!!

2023-10-07 05:51 UTC, egonw requested changes

2023-10-07 05:51 UTC, egonw commented on src/test/java/org/xmlcml/cml/element/main/CMLBandListTest.java
> + *    Copyright 2011 Peter Murray-Rust et. al.
Hi, the copyright statement format is as followed. First, in most countries the author or authors of a patch is/are the copyright holder. If you copied and started with code from someone else, that copyright is indeed often kept. But the copyright statement should also have the year of the new code (2023) and the name of the author. Your name, if you write the code all by yourself.

Please update the copyright statements. This is important to us to be compatible with projects like Debian, Red Hat, etc.

2023-10-14 12:29 UTC, merged